"""提供协议绑定、通用方法，需要使用者自行配置"""

from __future__ import annotations

# import inspect
# import pathlib
from types import MethodType
from typing import Callable, Type, TypeVar, Union

from .jtag import Jtag
from .serial import Serial
from .ssh import SSH
from .telnet import Telnet

Protocol = Union[SSH, Telnet, Jtag, Serial]
P = TypeVar("P", SSH, Telnet, Jtag, Serial)


# # 获取抽象的动态方法类
# script_dir = pathlib.Path(__file__).resolve().parent
# try:
#     from .meta_dynamic import DynamicMethods
# except Exception as _:
#     with open(script_dir / "meta_dynamic.py", "w") as f:
#         f.write("class DynamicMethods:\n    pass")
#     from .meta_dynamic import DynamicMethods


class DUTConfiguratorBase:
    """DUT配置器基类，提供协议绑定、通用方法，考虑多个重复类型的协议绑定\n
    应将其视作对于具体产品测试的配置基类\n
    用户继承此类进行产品测试行为细节的规定"""

    def __init__(self, *protocols: Protocol):
        """初始化参数传入需要操作的协议实例"""
        self.protocols: list[Protocol] = list(protocols)  # 存储协议实例
        self.dynamic_methods: dict[str, Callable] = {}  # 存储动态方法
        self.dynamic_methods_info: list[str] = []
        self.dynamic_modules: list[str] = []
        # self.script_dir = pathlib.Path(__file__).resolve().parent

    def get_protocol(self, protocol_type: Type[P]) -> list[P]:
        """获取指定类型的协议实例，实例存在返回所有该类型实例的列表，实例不存在返空列表"""
        res = []
        for p in self.protocols:
            if isinstance(p, protocol_type):
                res.append(p)
        return res

    def get_from_name(self, protocol_type: Type[P], name: str) -> P:
        """通过协议名称获取协议实例，实例存在返回该实例，实例不存在抛出异常"""
        for p in self.protocols:
            if isinstance(p, protocol_type) and p.name == name:
                return p
        raise KeyError(f"No protocol of name '{name}' found")

    def is_protocol_exist(self, protocol_type: Type[P]) -> bool:
        """判断是否存在指定类型的协议实例"""
        for p in self.protocols:
            if isinstance(p, protocol_type):
                return True
        return False

    def __getitem__(self, protocol: Type[P]) -> list[P]:
        """支持通过`self[Protocol]`语法获取协议实例列表\n
        获取失败会抛出异常"""
        res = self.get_protocol(protocol)
        if len(res) == 0:
            raise KeyError(f"No protocol of type {protocol} found")
        return res

    def __contains__(self, protocol_type_or_name: Type[P] | str) -> bool:
        """支持通过`Protocol in self`语法判断是否存在指定类型的协议实例"""
        if isinstance(protocol_type_or_name, str):
            return any(p.name == protocol_type_or_name for p in self.protocols)
        elif isinstance(protocol_type_or_name, type):
            return self.is_protocol_exist(protocol_type_or_name)

        else:
            raise TypeError(
                f"Unsupported type {type(protocol_type_or_name)} for protocol type"
            )
            # return False

    def add_dynamic_method(self, name: str, func: Callable):
        """注册动态方法，通过`self.name`调用"""
        # func_types = get_function_types_as_str(func)
        # pprint(func_types)
        self.dynamic_methods[name] = MethodType(func, self)
        # func_args = ", ".join(
        # f"{param}: {param_type}" for param, param_type in func_types[0].items()
        # )

    #         func_return = func_types[1]
    #         self.dynamic_methods_info.append(
    #             f"""    def {name}(self,{func_args}) -> {func_return}:
    #         '''{"\n        ".join(info.splitlines())}'''
    #         ...
    # """
    # )
    # pprint(self.dynamic_methods_pyi_info[-1])
    # with open(script_dir / "meta_dynamic.py", "a") as f:
    # f.write(self.dynamic_methods_info[-1] + "\n")

    # def add_dynamic_module(self, from_module: str, *import_objects: str):
    #     """添加生成的动态方法依赖"""
    #     self.dynamic_modules.append(
    #         f"from {from_module} import " + ", ".join(import_objects)
    #     )

    # def register_all_dynamic_methods(self):
    #     """注册动态方法到DynamicMethods类中"""
    #     with open(script_dir / "meta_dynamic.py", "w") as f:
    #         f.write("# This file is generated by metaclass.py, do not edit manually\n")
    #         for module in self.dynamic_modules:
    #             f.write(module + "\n")
    #         f.write("class DynamicMethods:\n")
    #         f.write("    def __init__(self):\n")
    #         f.write("        pass\n")

    #         for methods in self.dynamic_methods_info:
    #             f.write(methods + "\n")

    def __getattr__(self, dynamic_method: str) -> Callable:
        """获取动态方法"""
        # print(f"{dynamic_method = }")
        if func := self.dynamic_methods.get(dynamic_method):
            return func
        raise AttributeError(f"No dynamic method '{dynamic_method}' found")


# # 此函数为AI生成
# def get_function_types_as_str(func: Any) -> tuple[Dict[str, str], str]:
#     """
#     解析函数的参数类型和返回值类型，返回字符串表示，适合用于生成源代码中的类型注解。

#     参数:
#         func: 可调用对象（函数、方法、lambda 等）

#     返回:
#         tuple[Dict[str, str], str]
#     示例:
#         def example(a: int, b: str = "x") -> bool: ...
#         get_function_types_as_str(example)
#         # 返回: ( {'a': 'int', 'b': 'str'}, 'bool')

#     注意:
#         - 如果函数使用了 `from __future__ import annotations`，注解中的字符串会被原样保留（如 'List[int]'）。
#         - 如果注解是类型对象（如 int, str），则返回其 __name__（如 'int', 'str'）。
#         - 对于复杂泛型（如 List[int]），建议在函数注解中直接使用字符串（配合 future import）以获得精确表示。
#         - 缺失注解的参数/返回值默认为 'Any'。
#     """
#     sig = inspect.signature(func)
#     ann = getattr(func, "__annotations__", {})

#     param_types = {}
#     for name in sig.parameters:
#         if name in ann:
#             val = ann[name]
#             if isinstance(val, str):
#                 param_types[name] = val
#             else:
#                 # 提取类型名称（如 int -> 'int'，但 List[int] 会变成 'List'，丢失泛型参数）
#                 # 对于简单类型足够，复杂类型建议使用字符串注解
#                 param_types[name] = getattr(val, "__name__", str(val))
#         else:
#             param_types[name] = "Any"

#     ret_val = ann.get("return", "Any")
#     if not isinstance(ret_val, str):
#         ret_val = str(getattr(ret_val, "__name__", str(ret_val)))

#     return param_types, ret_val
